/*
 * Benwalden service worker
 * -------------------------
 * Goal: aggressive caching so the site works fully offline, while online
 * visitors always get the freshest content and live data.
 *
 * Strategy by request type:
 *   - HTML navigations         -> network-first (fresh when online, cached offline)
 *   - Live JSON feeds (APIs)   -> network-first (fresh when online, last-known offline)
 *   - Static assets & fonts    -> stale-while-revalidate (instant + refreshed in bg)
 *
 * Bump CACHE_VERSION whenever the precached shell changes so old caches are
 * purged on activation.
 */

const CACHE_VERSION = 'v3';
const PRECACHE = `benwalden-precache-${CACHE_VERSION}`;
const RUNTIME = `benwalden-runtime-${CACHE_VERSION}`;

// The app shell — everything needed to render the site with no network.
const PRECACHE_URLS = [
  '/',
  '/index.html',
  '/bg.webp',
  '/looncallalert.mp3',
  '/trails.json',
  '/trailcam/',
  '/trailcam/index.html',
  // trailcam-images:start (auto-generated by build-trailcam.sh — do not edit by hand)
  '/trailcam/images/IMG_0007.webp',
  '/trailcam/images/IMG_0018.webp',
  '/trailcam/images/IMG_0059.webp',
  '/trailcam/images/IMG_0082.webp',
  '/trailcam/images/IMG_0094.webp',
  '/trailcam/images/IMG_0099.webp',
  '/trailcam/images/IMG_0122.webp',
  '/trailcam/images/IMG_0216.webp',
  '/trailcam/images/IMG_0221.webp',
  '/trailcam/images/IMG_0222.webp',
  '/trailcam/images/IMG_0315.webp',
  '/trailcam/images/IMG_0347.webp',
  '/trailcam/images/IMG_0351.webp',
  '/trailcam/images/IMG_0382.webp',
  '/trailcam/images/IMG_0499.webp',
  '/trailcam/images/IMG_0514.webp',
  '/trailcam/images/IMG_0547.webp',
  '/trailcam/images/IMG_0553.webp',
  '/trailcam/images/IMG_0795.webp',
  // trailcam-images:end
];

// Hosts serving live data — always try the network first so online visitors
// see up-to-date weather / bird / business info, falling back to cache offline.
const API_HOSTS = [
  'weather.benwaldencab.in',
  'birdweather.benwaldencab.in',
  'admin.benwaldencab.in',
];

// ---- Install: precache the app shell -------------------------------------
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(PRECACHE).then((cache) =>
      // addAll is atomic (any 404 aborts the whole install), so add items
      // individually and tolerate the occasional missing asset.
      Promise.allSettled(
        PRECACHE_URLS.map((url) =>
          cache.add(new Request(url, { cache: 'reload' }))
        )
      )
    )
  );
  // Activate this new worker as soon as it finishes installing.
  self.skipWaiting();
});

// ---- Activate: drop stale caches -----------------------------------------
self.addEventListener('activate', (event) => {
  const keep = new Set([PRECACHE, RUNTIME]);
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(keys.filter((k) => !keep.has(k)).map((k) => caches.delete(k)))
      )
      .then(() => self.clients.claim())
  );
});

// Allow the page to tell a waiting worker to take over immediately.
self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting();
});

// ---- Fetch routing --------------------------------------------------------
self.addEventListener('fetch', (event) => {
  const { request } = event;

  // Only handle GETs; leave POSTs etc. to the network untouched.
  if (request.method !== 'GET') return;

  let url;
  try {
    url = new URL(request.url);
  } catch (e) {
    return;
  }

  // Only handle http(s) — skip chrome-extension:, data:, etc.
  if (url.protocol !== 'http:' && url.protocol !== 'https:') return;

  // HTML navigations -> network-first.
  if (
    request.mode === 'navigate' ||
    (request.headers.get('accept') || '').includes('text/html')
  ) {
    event.respondWith(networkFirst(request, PRECACHE, '/index.html'));
    return;
  }

  // Live data feeds -> network-first.
  if (API_HOSTS.includes(url.hostname)) {
    event.respondWith(networkFirst(request, RUNTIME));
    return;
  }

  // Everything else (assets, fonts, css) -> stale-while-revalidate.
  event.respondWith(staleWhileRevalidate(request, RUNTIME));
});

// ---- Strategies -----------------------------------------------------------

// Network-first: return the live response when reachable and cache it;
// otherwise serve the cached copy (or an optional fallback URL).
async function networkFirst(request, cacheName, fallbackUrl) {
  const cache = await caches.open(cacheName);
  try {
    const response = await fetch(request);
    if (response && (response.ok || response.type === 'opaque')) {
      cache.put(request, response.clone());
    }
    return response;
  } catch (e) {
    const cached = await cache.match(request);
    if (cached) return cached;
    if (fallbackUrl) {
      const fallback = await caches.match(fallbackUrl);
      if (fallback) return fallback;
    }
    return Response.error();
  }
}

// Stale-while-revalidate: serve cache immediately (fast + offline) and
// refresh the cached copy in the background for next time.
async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(cacheName);
  const cached = await cache.match(request);

  const network = fetch(request)
    .then((response) => {
      if (response && (response.ok || response.type === 'opaque')) {
        cache.put(request, response.clone());
      }
      return response;
    })
    .catch(() => null);

  return cached || (await network) || Response.error();
}
